version: '1'

networks:
  default:
    name: nextcloud

services:
  db:
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
     - ./db:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=1h2j3k<>
     - MYSQL_DATABASE=nextcloud
     - MYSQL_USER=nextcloud
     - MYSQL_PASSWORD=1h2j3k<>
    networks:
      - default

  app:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    volumes:
     - ./app:/var/www/html
    environment:
     - MYSQL_DATABASE=nextcloud
     - MYSQL_USER=nextcloud
     - MYSQL_PASSWORD=1h2j3k<>
     - MYSQL_HOST=db
    ports:
      - 7788:80
    networks:
      - default

  cache:
    image: redis
    restart: unless-stopped
    expose:
    - "6379"
    volumes:
      - ./cache:/data
    command: redis-server --requirepass '1h2j3k<>'
    networks:
      - default